version: "3.9"

services:

  db:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - .env
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: ocranno
      MYSQL_USER: db_user
      MYSQL_PASSWORD: my_secret_password
      MYSQL_ROOT_PASSWORD: my_secret_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  ocranno:
    container_name: ocranno_app
    command: sh -c "composer update && composer install && php artisan serve --host=0.0.0.0 --port=8080"
    links:
      - db
      - phpmyadmin
    build:
      args:
        user: sammy
        uid: 1000
      context: .
    ports:
      - 8080:8080
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./:/var/www

networks:
  default:
    external:
      name: ocranno-network

volumes:
  dbdata:
